{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Stable-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Stable-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Stable-SNAPSHOT.aar",
          "url": "native-Stable-SNAPSHOT.aar",
          "size": 16403079,
          "sha512": "1ce499b29d3b4743d71537adeff761c81d4beb2c86b5d3d69e911001f8ae7ec759aa742d14bbf164b72a7e0458ef6d9cccd4cb76b8c70f77f7fbf2728e594cc5",
          "sha256": "dd4160391e13f76082ae059bd38a65ddec6e22b1d508c259925233bc3776dc80",
          "sha1": "0dfda2b9fa72ed53479ba981ca740b9dc16614be",
          "md5": "2348e1ddd5ec1e52bb7256a84ba8fa6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Stable-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Stable-SNAPSHOT.aar",
          "url": "native-Stable-SNAPSHOT.aar",
          "size": 16403079,
          "sha512": "1ce499b29d3b4743d71537adeff761c81d4beb2c86b5d3d69e911001f8ae7ec759aa742d14bbf164b72a7e0458ef6d9cccd4cb76b8c70f77f7fbf2728e594cc5",
          "sha256": "dd4160391e13f76082ae059bd38a65ddec6e22b1d508c259925233bc3776dc80",
          "sha1": "0dfda2b9fa72ed53479ba981ca740b9dc16614be",
          "md5": "2348e1ddd5ec1e52bb7256a84ba8fa6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Stable-SNAPSHOT-sources.jar",
          "url": "native-Stable-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
