{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Stable-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Stable-SNAPSHOT.aar",
          "url": "core-Stable-SNAPSHOT.aar",
          "size": 1275919,
          "sha512": "0394593b1f4af9a862b447d2e228281acfbe40a02f61d731af97b64c5d359b61eb6cf45ede2462cd3652d2b73c9536dc9f5abb473fd0ceaaadebade135fb8d4c",
          "sha256": "11a815c420a56fc63e46e203efc0b707566433b6258b2b84b1df994eb6c15764",
          "sha1": "26ad42c9950c434fd3d177c9f1fd0f1657fd953b",
          "md5": "a3af51e452df4d2abea16bf6e3aac611"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Stable-SNAPSHOT.aar",
          "url": "core-Stable-SNAPSHOT.aar",
          "size": 1275919,
          "sha512": "0394593b1f4af9a862b447d2e228281acfbe40a02f61d731af97b64c5d359b61eb6cf45ede2462cd3652d2b73c9536dc9f5abb473fd0ceaaadebade135fb8d4c",
          "sha256": "11a815c420a56fc63e46e203efc0b707566433b6258b2b84b1df994eb6c15764",
          "sha1": "26ad42c9950c434fd3d177c9f1fd0f1657fd953b",
          "md5": "a3af51e452df4d2abea16bf6e3aac611"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Stable-SNAPSHOT-sources.jar",
          "url": "core-Stable-SNAPSHOT-sources.jar",
          "size": 13801,
          "sha512": "550673180bedd06aa31cbcfee0b3aad00838d93678af8d42d63aeb401992785b4a8f526b1394ebafcc9403a8e6c19019a71d3d5455881785ed53cf879c1415a2",
          "sha256": "a1f0a485c1e32b6c18e222eed75b44483ac39fe9d4e75042a5874b0636d6c42b",
          "sha1": "3cf04e3bccaa76c507058cd371f7939bc9694a35",
          "md5": "124bb30a7a6a43125e58cb27b5772c70"
        }
      ]
    }
  ]
}
