{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Stable-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Stable-SNAPSHOT.aar",
          "url": "core-Stable-SNAPSHOT.aar",
          "size": 1277970,
          "sha512": "4f45b03f3da344113a6a94b989b7c9f21fa656544798ff37aeff2e189245e3b8274c4829679a6e8e6775d29c3bd386ef342367f9d7fd32be665f0c6123b34dfe",
          "sha256": "2d4b56cf5b227d646b86802f2eefb956cd13c9fd872032d45707ec279f13bd3f",
          "sha1": "2b0783ff57dda69eafb2d20837df251718ee41d0",
          "md5": "9661541e06f6d2466dcb35f6d7d72813"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Stable-SNAPSHOT.aar",
          "url": "core-Stable-SNAPSHOT.aar",
          "size": 1277970,
          "sha512": "4f45b03f3da344113a6a94b989b7c9f21fa656544798ff37aeff2e189245e3b8274c4829679a6e8e6775d29c3bd386ef342367f9d7fd32be665f0c6123b34dfe",
          "sha256": "2d4b56cf5b227d646b86802f2eefb956cd13c9fd872032d45707ec279f13bd3f",
          "sha1": "2b0783ff57dda69eafb2d20837df251718ee41d0",
          "md5": "9661541e06f6d2466dcb35f6d7d72813"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Stable-SNAPSHOT-sources.jar",
          "url": "core-Stable-SNAPSHOT-sources.jar",
          "size": 13802,
          "sha512": "b645dbb0695f95686ecd39bae6b46ca808d8e0e30338930d10818ab356a70d1cab58a26a3de971592ae80f53621116b65c71d79922bcc1df7bfdbfd1e2fdeec5",
          "sha256": "407ad49b67cd789c288310add9c3320aa20fba7471d4a3d599fa37afd23e6011",
          "sha1": "aac94ceebc1619ca27704f5b0b78a67e45e906d3",
          "md5": "b5035b0d8657500eed4c87afa1990933"
        }
      ]
    }
  ]
}
