{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Stable-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Stable-SNAPSHOT.aar",
          "url": "core-Stable-SNAPSHOT.aar",
          "size": 1275911,
          "sha512": "6377cdc86d4a4106675e9176d0de1f836cb8d0eaa993d28031ccc3643a02a6f663b6375bf9305ff93d85dd4901056a659d03b93feb35c3653b34fc7803716e00",
          "sha256": "77070a3a3abb8724012da3fa49f2a856a8e84a8f038d6c27044f62f475886de3",
          "sha1": "6bb40fb80a69567cf3f03f119525bb3ef4bea969",
          "md5": "4f2e7101ca478bc9b78fb91140fca09b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Stable-SNAPSHOT.aar",
          "url": "core-Stable-SNAPSHOT.aar",
          "size": 1275911,
          "sha512": "6377cdc86d4a4106675e9176d0de1f836cb8d0eaa993d28031ccc3643a02a6f663b6375bf9305ff93d85dd4901056a659d03b93feb35c3653b34fc7803716e00",
          "sha256": "77070a3a3abb8724012da3fa49f2a856a8e84a8f038d6c27044f62f475886de3",
          "sha1": "6bb40fb80a69567cf3f03f119525bb3ef4bea969",
          "md5": "4f2e7101ca478bc9b78fb91140fca09b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Stable-SNAPSHOT-sources.jar",
          "url": "core-Stable-SNAPSHOT-sources.jar",
          "size": 13801,
          "sha512": "d74bb7b876187cc653f6a7452b4a30a52f672c68ed1600fe08913c29bd624c46d0bc5b8d5cf438d78d1993a25c0b4432ed6ca4afd54d513b163afe67b84a1a99",
          "sha256": "98632eaa97081bc6d4dea144465ca0674ac1d0253831d512cedbee485132062c",
          "sha1": "11a64d9d5b0504b3df67d8cc7cb399714bbffa0e",
          "md5": "6c97dc9aae9d348bdbf4688c912259f6"
        }
      ]
    }
  ]
}
