{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Dev-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Dev-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Dev-SNAPSHOT.aar",
          "url": "native-Dev-SNAPSHOT.aar",
          "size": 16482862,
          "sha512": "3aaae91a9ef8286f3280ec3d2efc554074f3810c4b68066de4fa432953e0885159d202d16d2166da19a7e08ea8717747475a30db58ceee487b49b5d73078b4a9",
          "sha256": "79bfe2e5a21958c24aab9edc65e65b12f34e69e4cebac2b32294d399e4c6a4ec",
          "sha1": "dce4b83834a87a389162b1b684932dfd2a6457b0",
          "md5": "bc40dd4ac9efa85c4fecdfcd07c554dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Dev-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Dev-SNAPSHOT.aar",
          "url": "native-Dev-SNAPSHOT.aar",
          "size": 16482862,
          "sha512": "3aaae91a9ef8286f3280ec3d2efc554074f3810c4b68066de4fa432953e0885159d202d16d2166da19a7e08ea8717747475a30db58ceee487b49b5d73078b4a9",
          "sha256": "79bfe2e5a21958c24aab9edc65e65b12f34e69e4cebac2b32294d399e4c6a4ec",
          "sha1": "dce4b83834a87a389162b1b684932dfd2a6457b0",
          "md5": "bc40dd4ac9efa85c4fecdfcd07c554dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Dev-SNAPSHOT-sources.jar",
          "url": "native-Dev-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
