{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Dev-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Dev-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Dev-SNAPSHOT.aar",
          "url": "native-Dev-SNAPSHOT.aar",
          "size": 16587750,
          "sha512": "a6d5aaa94d7c6c4eaf5cb445eee2b25c60ac26587c16a1f792b676bc0156ae39e249dd8a1eb68519a9c6cece38067e68f2282fca633e290eab025ed77401e938",
          "sha256": "faea5da69c00abf120515ce5606a47a21a7ea7a0bf0a9f7006928bcbe7aa148f",
          "sha1": "b7dd0f9780288944163456771d663794501dfd20",
          "md5": "813a273a74558cb5c091859080cd3720"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Dev-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Dev-SNAPSHOT.aar",
          "url": "native-Dev-SNAPSHOT.aar",
          "size": 16587750,
          "sha512": "a6d5aaa94d7c6c4eaf5cb445eee2b25c60ac26587c16a1f792b676bc0156ae39e249dd8a1eb68519a9c6cece38067e68f2282fca633e290eab025ed77401e938",
          "sha256": "faea5da69c00abf120515ce5606a47a21a7ea7a0bf0a9f7006928bcbe7aa148f",
          "sha1": "b7dd0f9780288944163456771d663794501dfd20",
          "md5": "813a273a74558cb5c091859080cd3720"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Dev-SNAPSHOT-sources.jar",
          "url": "native-Dev-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
