{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Dev-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Dev-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Dev-SNAPSHOT.aar",
          "url": "native-Dev-SNAPSHOT.aar",
          "size": 16487283,
          "sha512": "67fc7c835f62037dacd604cbbbad8775b552037dc53e48e822f701f7ae0d8d6bd6700ecdf561bbb7ed57f44400dd0c5f6d1b29c43b88a95a7dcffa5bb06374ac",
          "sha256": "3d3a14ddd9511597d9f1613bae2ea2de1dd5b8f31ab6592c1fab20241141ac98",
          "sha1": "f4d88c39a47db9961cda9424ae450973580ba986",
          "md5": "ffe4d37ba92dd3ac598328ec168d64a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Dev-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Dev-SNAPSHOT.aar",
          "url": "native-Dev-SNAPSHOT.aar",
          "size": 16487283,
          "sha512": "67fc7c835f62037dacd604cbbbad8775b552037dc53e48e822f701f7ae0d8d6bd6700ecdf561bbb7ed57f44400dd0c5f6d1b29c43b88a95a7dcffa5bb06374ac",
          "sha256": "3d3a14ddd9511597d9f1613bae2ea2de1dd5b8f31ab6592c1fab20241141ac98",
          "sha1": "f4d88c39a47db9961cda9424ae450973580ba986",
          "md5": "ffe4d37ba92dd3ac598328ec168d64a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Dev-SNAPSHOT-sources.jar",
          "url": "native-Dev-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
