{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.1.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-local.aar",
          "url": "core-local.aar",
          "size": 456588,
          "sha512": "2aaa5e2979a51205778a28a8690f6ffb3fd4276a73193f6fcc58f815b5e207b5f05d0951ac483820a0d2b589cafcf784c1136de2a2504363e3458b0240b87c79",
          "sha256": "c8a5aff32a337d8152ee4519dea558f0e43bca73334f4d1e7a2883c958b3bcc5",
          "sha1": "71f8971f14bd797fc38928423de2ce2071c323d2",
          "md5": "582a0bb8a2dbc64faf18b63e771896a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.1.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-local.aar",
          "url": "core-local.aar",
          "size": 456588,
          "sha512": "2aaa5e2979a51205778a28a8690f6ffb3fd4276a73193f6fcc58f815b5e207b5f05d0951ac483820a0d2b589cafcf784c1136de2a2504363e3458b0240b87c79",
          "sha256": "c8a5aff32a337d8152ee4519dea558f0e43bca73334f4d1e7a2883c958b3bcc5",
          "sha1": "71f8971f14bd797fc38928423de2ce2071c323d2",
          "md5": "582a0bb8a2dbc64faf18b63e771896a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-local-sources.jar",
          "url": "core-local-sources.jar",
          "size": 14280,
          "sha512": "4334d5839a0b46563a89e53e24478c63b6e773d871537a4b1dae2411e9a67d89e9a7fa9378505f4b7a4f12f692dae17190954ff3712bb18c1b5f3be159a75e97",
          "sha256": "cfe66f6931335e8f204a4643cb802c4cf675a209b2f825de8d809968151237fd",
          "sha1": "81a4dc1d222fe610c96feab34e902b3a0af88bfb",
          "md5": "b1f3760d552fa727e0adbb13613bb395"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-local-javadoc.jar",
          "url": "core-local-javadoc.jar",
          "size": 320934,
          "sha512": "3516211651c20986af5654950424dc8f3741f926498bb3b4cea216abe800f4a2e9c6945d5a8c587c077308b78fa00d3b987b4673de8c96298baf924c12c087c6",
          "sha256": "7b3e754b4fd794acaf95bc9b7732c3de9eecc3e2ea8fb72db06d9d067a7ea4a4",
          "sha1": "94248d8d60ed51daaaa2b69d48b637dee2ab5d14",
          "md5": "20a989908d46c57721a3a6d465dedb5f"
        }
      ]
    }
  ]
}
