{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "okhttp",
    "version": "local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "local"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-local.aar",
          "url": "okhttp-local.aar",
          "size": 11630,
          "sha512": "ef262c409296c4c9afe424296e0086abe75bd0080dd54a5e0faf66583461b0a49f41b2b3e3b089e68e7205b1a138af6d0ddc00bf6ee7cc9050e5a8fe113ab025",
          "sha256": "dfd53ce90860aad5a834050571b19c6c6044f20ed173f2ee02eaaccfbe56cdaa",
          "sha1": "9803f4e0d695826f6b3b7de01583a6c1268161c0",
          "md5": "1e2ab6c9d73ca414b10843596ca83312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "local"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-local.aar",
          "url": "okhttp-local.aar",
          "size": 11630,
          "sha512": "ef262c409296c4c9afe424296e0086abe75bd0080dd54a5e0faf66583461b0a49f41b2b3e3b089e68e7205b1a138af6d0ddc00bf6ee7cc9050e5a8fe113ab025",
          "sha256": "dfd53ce90860aad5a834050571b19c6c6044f20ed173f2ee02eaaccfbe56cdaa",
          "sha1": "9803f4e0d695826f6b3b7de01583a6c1268161c0",
          "md5": "1e2ab6c9d73ca414b10843596ca83312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-local-sources.jar",
          "url": "okhttp-local-sources.jar",
          "size": 6907,
          "sha512": "300fcc82a15f09411829d5b4efc38b58428a62d7a792df64eabfe33c7c100fef3981d5696d6244fb4d27eb8478b8573a77d0bd1ad07bf5764af57d00a72672b8",
          "sha256": "afbe049d984db4d35be365957785eb3d0b33f070cc932d2d2edcd6274aaef96f",
          "sha1": "227025876e51f7599137a7cedce88c836eb150e0",
          "md5": "bdf18fe471db6952a6e0cee9acd1f78d"
        }
      ]
    }
  ]
}
