{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Canary-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Canary-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Canary-SNAPSHOT.aar",
          "url": "native-Canary-SNAPSHOT.aar",
          "size": 16596323,
          "sha512": "01fea1ac6ce195a31aaa70e30de453599d1f8e61c5b3528db93df8707812fd617c5628c4a1dd535d9a78947e5de76d03846d31fbf7e649660352765ff5e647d1",
          "sha256": "0419fdd5e13b6a0a239988d23f9b0669536d60be99803fbc35bb3bb5045adb40",
          "sha1": "3dd468c57388444f2a1a545153479064ff4565ff",
          "md5": "a222b2f54db252de75ccc5df4d665b9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Canary-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Canary-SNAPSHOT.aar",
          "url": "native-Canary-SNAPSHOT.aar",
          "size": 16596323,
          "sha512": "01fea1ac6ce195a31aaa70e30de453599d1f8e61c5b3528db93df8707812fd617c5628c4a1dd535d9a78947e5de76d03846d31fbf7e649660352765ff5e647d1",
          "sha256": "0419fdd5e13b6a0a239988d23f9b0669536d60be99803fbc35bb3bb5045adb40",
          "sha1": "3dd468c57388444f2a1a545153479064ff4565ff",
          "md5": "a222b2f54db252de75ccc5df4d665b9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Canary-SNAPSHOT-sources.jar",
          "url": "native-Canary-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
