{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Canary-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Canary-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "native-Canary-SNAPSHOT.aar",
          "url": "native-Canary-SNAPSHOT.aar",
          "size": 12241302,
          "sha512": "319891fa51d4838ea4b1b1960fb54c264cee415d3bd7806bc355dc32606926698f5e7a129a9249f157befcdad16f61305a19c72db5322684d74fdbc888ddbe72",
          "sha256": "c190907eaf790332cb05328aa8be399c4829fd042e2951096edf7905283cc4e3",
          "sha1": "8296e93827124bd7aeeb96ba236acec8d733a60d",
          "md5": "686fb46d41d27bc732678aba1bb4a0a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Canary-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "native-Canary-SNAPSHOT.aar",
          "url": "native-Canary-SNAPSHOT.aar",
          "size": 12241302,
          "sha512": "319891fa51d4838ea4b1b1960fb54c264cee415d3bd7806bc355dc32606926698f5e7a129a9249f157befcdad16f61305a19c72db5322684d74fdbc888ddbe72",
          "sha256": "c190907eaf790332cb05328aa8be399c4829fd042e2951096edf7905283cc4e3",
          "sha1": "8296e93827124bd7aeeb96ba236acec8d733a60d",
          "md5": "686fb46d41d27bc732678aba1bb4a0a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Canary-SNAPSHOT-sources.jar",
          "url": "native-Canary-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
