{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "okhttp-kt",
    "version": "local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "okhttp",
          "version": {
            "requires": "local"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-kt-local.aar",
          "url": "okhttp-kt-local.aar",
          "size": 7121,
          "sha512": "67011183a2be878e404c38dae17c5f963f7fcf12d4b8f68b46d9c4b164b37707cec86b3f4671f3cda757200217f5b531f3db06cae747ea33af592fabbda74c66",
          "sha256": "54d605cdbcb23146ea2d9f5c3fc839d4ae2822cd2f16ebcbd5e177c6735b49e4",
          "sha1": "7013a3c116b2939f32a358a0a5526953516e5529",
          "md5": "d2b0ce2a02bf9a00254cae1cbe02d9f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "okhttp",
          "version": {
            "requires": "local"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-kt-local.aar",
          "url": "okhttp-kt-local.aar",
          "size": 7121,
          "sha512": "67011183a2be878e404c38dae17c5f963f7fcf12d4b8f68b46d9c4b164b37707cec86b3f4671f3cda757200217f5b531f3db06cae747ea33af592fabbda74c66",
          "sha256": "54d605cdbcb23146ea2d9f5c3fc839d4ae2822cd2f16ebcbd5e177c6735b49e4",
          "sha1": "7013a3c116b2939f32a358a0a5526953516e5529",
          "md5": "d2b0ce2a02bf9a00254cae1cbe02d9f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-kt-local-sources.jar",
          "url": "okhttp-kt-local-sources.jar",
          "size": 1606,
          "sha512": "6074e2bd2b58bfe605e8b82556448890d0a56871c5e867a8b4dfd231ff257081ba3a146dc8ac7105837a5fc466c288da41a72eef86a754d3736d151c51516eff",
          "sha256": "8c66b9d690ad74f43eeb2d0816260e33785cf91a63fd03138a4acfefff6e97f5",
          "sha1": "2ff18ff1f43c05c2ab568e6dbd8004a317e65d86",
          "md5": "f800e22b24cc45cec965e29d5f6a4fc8"
        }
      ]
    }
  ]
}
