{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "okhttp",
    "version": "Canary-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Canary-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-Canary-SNAPSHOT.aar",
          "url": "okhttp-Canary-SNAPSHOT.aar",
          "size": 34409,
          "sha512": "d244999910b0e24ded545257744fae9eab64a7e9072baf0102c2c15f1d10346031d5e8bfea552ae9d6ab84911f18d14e8c8df6d9ce9a6b66e573e7b6466eec25",
          "sha256": "aeea17482b6173bdb64dcac6e7d3e2149d8448a0aa0b0f2b4f48da77269b732e",
          "sha1": "213f1c624350759143ffd81d9b8dca160212aaad",
          "md5": "c14c6de0379423016f3d0a02250ceb76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Canary-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-Canary-SNAPSHOT.aar",
          "url": "okhttp-Canary-SNAPSHOT.aar",
          "size": 34409,
          "sha512": "d244999910b0e24ded545257744fae9eab64a7e9072baf0102c2c15f1d10346031d5e8bfea552ae9d6ab84911f18d14e8c8df6d9ce9a6b66e573e7b6466eec25",
          "sha256": "aeea17482b6173bdb64dcac6e7d3e2149d8448a0aa0b0f2b4f48da77269b732e",
          "sha1": "213f1c624350759143ffd81d9b8dca160212aaad",
          "md5": "c14c6de0379423016f3d0a02250ceb76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-Canary-SNAPSHOT-sources.jar",
          "url": "okhttp-Canary-SNAPSHOT-sources.jar",
          "size": 19201,
          "sha512": "de1466e5355de550c634cc53726f98957f7cd15fd6ba7c73b7610d4f5f9e29b2f8100daca66a1a161b523c197191a915ca6bb0a12a197a60b87553b9d63350fe",
          "sha256": "7e0d088f30c1329c786c2b64f73dd1da69bbb09d5dec53f8e61b413cc30410ec",
          "sha1": "35b18c275b6cf504d0351dc9009587ee40941e81",
          "md5": "e85760cc262f240ba1078c9d3bd53804"
        }
      ]
    }
  ]
}
