{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Dev-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Dev-SNAPSHOT.aar",
          "url": "core-Dev-SNAPSHOT.aar",
          "size": 1285181,
          "sha512": "4838d4864a27a41976aef9b9b13f4810a738a9890020990573cd26e635c7cf9c4b9f95a8adb4ea657033539774a2b2c77e712ce72f6c9900140b0f45bc44c35a",
          "sha256": "8d37f955413b7c03355183f98aed7eb036edb2846246bdab9cd520878d360a76",
          "sha1": "c3024a4c484de2473def72a7acfa764936efbaef",
          "md5": "4294bfff8c23360d40d4c55cc45d9401"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Dev-SNAPSHOT.aar",
          "url": "core-Dev-SNAPSHOT.aar",
          "size": 1285181,
          "sha512": "4838d4864a27a41976aef9b9b13f4810a738a9890020990573cd26e635c7cf9c4b9f95a8adb4ea657033539774a2b2c77e712ce72f6c9900140b0f45bc44c35a",
          "sha256": "8d37f955413b7c03355183f98aed7eb036edb2846246bdab9cd520878d360a76",
          "sha1": "c3024a4c484de2473def72a7acfa764936efbaef",
          "md5": "4294bfff8c23360d40d4c55cc45d9401"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Dev-SNAPSHOT-sources.jar",
          "url": "core-Dev-SNAPSHOT-sources.jar",
          "size": 13800,
          "sha512": "29e6ae4de3da2af5c46dbd8a9f49a7b4e95f3b8068810ec05f55e99d7cd9356ab7c2d92738df04627cbef388e10eb244362eec4a5a194302bc7846685bb6e0b6",
          "sha256": "789e75b6ab7869273e5caf70827c1eb01bcd27031a724f5b07e4d6c4e7211bac",
          "sha1": "dcaf93405e91f9334d54547f537a1b15ac3ba6f9",
          "md5": "2d175d2dfaf79c390eb228a2136cbfb4"
        }
      ]
    }
  ]
}
