{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Dev-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Dev-SNAPSHOT.aar",
          "url": "core-Dev-SNAPSHOT.aar",
          "size": 1284024,
          "sha512": "be58db8e7431f2011c532473fafefe4d004a2f39384d15ca482b2bfcdcbf80f90c365def282f7b165c6d8a621aa82a344c8dbb3a4bb2a76765b2f7f0ee8b7f5a",
          "sha256": "0d250c5fb0f5d283d23f78fa8494a37f63bedc2dcb93b049eefd7ff9008a6a58",
          "sha1": "3591134259fb3fc5556ab3a91b5c2efa39fe8d5c",
          "md5": "8f2f7f4ad6fb4bd4b037c69fe72d58a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Dev-SNAPSHOT.aar",
          "url": "core-Dev-SNAPSHOT.aar",
          "size": 1284024,
          "sha512": "be58db8e7431f2011c532473fafefe4d004a2f39384d15ca482b2bfcdcbf80f90c365def282f7b165c6d8a621aa82a344c8dbb3a4bb2a76765b2f7f0ee8b7f5a",
          "sha256": "0d250c5fb0f5d283d23f78fa8494a37f63bedc2dcb93b049eefd7ff9008a6a58",
          "sha1": "3591134259fb3fc5556ab3a91b5c2efa39fe8d5c",
          "md5": "8f2f7f4ad6fb4bd4b037c69fe72d58a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Dev-SNAPSHOT-sources.jar",
          "url": "core-Dev-SNAPSHOT-sources.jar",
          "size": 13801,
          "sha512": "176198d28b5429e28b3f18d16e1e4e06b7476c5a3e0fbb455afb1450e341ef4ca4eac04de848c763b238735cfced8e96ae79f2c4b934c87b9846cfbd8b8bff5a",
          "sha256": "44d74abb8b26346ca1679e6cd5a54356b2342faf099a8ccc72b709dd8c8c37cd",
          "sha1": "f589acc2ed0ea4f244ff629b1940564aea45d2e9",
          "md5": "3833e2228242b78571db5acd6af86f20"
        }
      ]
    }
  ]
}
