{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Dev-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Dev-SNAPSHOT.aar",
          "url": "core-Dev-SNAPSHOT.aar",
          "size": 1281928,
          "sha512": "275277cdec7698fdbb416d65da2c794cb046ec05c794d0913b35ada53b7361c4fc78e1e2640dee1c0a06d69801f6291ebba994f3d6e53880f681817d5d8b33ec",
          "sha256": "3e5ceb864b887504e1b3bc3724d0cec7a35d582bb1a40c504d038e137ca97d95",
          "sha1": "69047d73809dd28f175630d885340a14642d71c4",
          "md5": "3c18c6a97f41a1bb409c3a416970a15d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Dev-SNAPSHOT.aar",
          "url": "core-Dev-SNAPSHOT.aar",
          "size": 1281928,
          "sha512": "275277cdec7698fdbb416d65da2c794cb046ec05c794d0913b35ada53b7361c4fc78e1e2640dee1c0a06d69801f6291ebba994f3d6e53880f681817d5d8b33ec",
          "sha256": "3e5ceb864b887504e1b3bc3724d0cec7a35d582bb1a40c504d038e137ca97d95",
          "sha1": "69047d73809dd28f175630d885340a14642d71c4",
          "md5": "3c18c6a97f41a1bb409c3a416970a15d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Dev-SNAPSHOT-sources.jar",
          "url": "core-Dev-SNAPSHOT-sources.jar",
          "size": 13800,
          "sha512": "50ac0d82af0f7a91919cd9bca14efe5f247ed10b047963711b4ea72e1a34b211880da90574dfe9b4903ae0b21040a9b22a0b023763da13b069520af42b8da7fe",
          "sha256": "48fc803ff67940bcc830c38b036bddebd4e0325f89ae654e53afdaec8224f732",
          "sha1": "a83221332516a3dc9cb480a84935728ca5d77cfc",
          "md5": "bbf9f54b9c1db2430468f6f8cbeafaae"
        }
      ]
    }
  ]
}
