{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Beta-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Beta-SNAPSHOT.aar",
          "url": "core-Beta-SNAPSHOT.aar",
          "size": 1284301,
          "sha512": "0b056765579f1f4ecfea40111b5e512ccb78ef6fb7497ded41708b4f16cc355c21128de0e467db1deef7bcff8ede8a68d4ac92b9a6a898ee71f6ab042379d976",
          "sha256": "89d1afc6a21b944ec4076ec53c082a2bd48c7ca0b56ad17e7f73c64b50b3f132",
          "sha1": "ed3625a5af1f7244722a29e76ffc475681679399",
          "md5": "c52c8c41f079223a3d449f1867674d4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Beta-SNAPSHOT.aar",
          "url": "core-Beta-SNAPSHOT.aar",
          "size": 1284301,
          "sha512": "0b056765579f1f4ecfea40111b5e512ccb78ef6fb7497ded41708b4f16cc355c21128de0e467db1deef7bcff8ede8a68d4ac92b9a6a898ee71f6ab042379d976",
          "sha256": "89d1afc6a21b944ec4076ec53c082a2bd48c7ca0b56ad17e7f73c64b50b3f132",
          "sha1": "ed3625a5af1f7244722a29e76ffc475681679399",
          "md5": "c52c8c41f079223a3d449f1867674d4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Beta-SNAPSHOT-sources.jar",
          "url": "core-Beta-SNAPSHOT-sources.jar",
          "size": 13800,
          "sha512": "6f1b8e9e57872d77698d2e058a03a90a286b1809b2a48c7f14d1724a3d17599b89b1cfaf5250f2a6874d598d2e02f5a9de60f251659137ee907cb64a4ca150f8",
          "sha256": "e8d57a095367c294189d6ff20b777921dc86616b9e1e28a7eb01aa316244b412",
          "sha1": "82f49e1f1e3291c1925d4e5296d66d3738e85051",
          "md5": "faf4902b7e97a12f7b60f8e7ce5cacad"
        }
      ]
    }
  ]
}
