{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Beta-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Beta-SNAPSHOT.aar",
          "url": "core-Beta-SNAPSHOT.aar",
          "size": 526716,
          "sha512": "c2ae43b40f1d3dfc9f88b086521613bc9aad09f23c2bfcdd6c02828e93f283b0743c2c078170ea94488154464fe26a315f56cf18f55a209c32d071b8a4fae271",
          "sha256": "8dadf5a58e2fa92b5376842007ecc97c5af744190bb04a45a520ab5bcacb04dc",
          "sha1": "d1b4e4fc620ecb1a7212bac57fc35af1fe8f060c",
          "md5": "2dde3c174f5e9502e12eda2369843bed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.25.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Beta-SNAPSHOT.aar",
          "url": "core-Beta-SNAPSHOT.aar",
          "size": 526716,
          "sha512": "c2ae43b40f1d3dfc9f88b086521613bc9aad09f23c2bfcdd6c02828e93f283b0743c2c078170ea94488154464fe26a315f56cf18f55a209c32d071b8a4fae271",
          "sha256": "8dadf5a58e2fa92b5376842007ecc97c5af744190bb04a45a520ab5bcacb04dc",
          "sha1": "d1b4e4fc620ecb1a7212bac57fc35af1fe8f060c",
          "md5": "2dde3c174f5e9502e12eda2369843bed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Beta-SNAPSHOT-sources.jar",
          "url": "core-Beta-SNAPSHOT-sources.jar",
          "size": 12476,
          "sha512": "49fba0faa9d35c37f6976e5a5ebb45593e428f01904e7749290be81bdfbc9d6b5e7807b2d68e69585e8132a7dd28a260415a6f619796a8d9d83795476fcf17a8",
          "sha256": "e1ce03fe73081ff38b36202f3b45f247cdc93b9c60a15b26ac388b9ce12355d4",
          "sha1": "8026222059ad7ba23274a2651d11d2ab29a6c79c",
          "md5": "d1f463316082a9fbaa15a59728f2acf6"
        }
      ]
    }
  ]
}
