{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "okhttp-kt",
    "version": "108.0.5359.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "okhttp",
          "version": {
            "requires": "108.0.5359.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-kt-108.0.5359.22.aar",
          "url": "okhttp-kt-108.0.5359.22.aar",
          "size": 7118,
          "sha512": "39f2f3bd5434fdd1e313d925af6984ce5d2e33f63d5101c1bbaddf82006f657b31458b6a9ba916667945d8f271ac4420372c6edb2aa3001c70a7f9e6be8e0333",
          "sha256": "b6f2fea1ca6f412f45a3049baf765d08828be5d993843232af21ba6d585ab953",
          "sha1": "6ff564596cd55aefee6ff0ebc4aa0aac730a2ad3",
          "md5": "add14b284cd5ab5f3c8149eac21e2f53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "okhttp",
          "version": {
            "requires": "108.0.5359.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-kt-108.0.5359.22.aar",
          "url": "okhttp-kt-108.0.5359.22.aar",
          "size": 7118,
          "sha512": "39f2f3bd5434fdd1e313d925af6984ce5d2e33f63d5101c1bbaddf82006f657b31458b6a9ba916667945d8f271ac4420372c6edb2aa3001c70a7f9e6be8e0333",
          "sha256": "b6f2fea1ca6f412f45a3049baf765d08828be5d993843232af21ba6d585ab953",
          "sha1": "6ff564596cd55aefee6ff0ebc4aa0aac730a2ad3",
          "md5": "add14b284cd5ab5f3c8149eac21e2f53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-kt-108.0.5359.22-sources.jar",
          "url": "okhttp-kt-108.0.5359.22-sources.jar",
          "size": 1595,
          "sha512": "672498c889806d170999c7030dcadfdbebbb4d7c4fbe349faad9cb9e06002eda97423c4c8478c23259acffb42765ad3f00bada39ee28c7adfce95054c8cdd7d2",
          "sha256": "f2563f1ef82dd4710f293d749ce2331dc6e4217ee13e11c2173e0320bd96b9ba",
          "sha1": "3663d58a827d363008d135cc36a863da216a04aa",
          "md5": "8c55f44f8333d70b64cfedd721aa9584"
        }
      ]
    }
  ]
}
