{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Beta-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Beta-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Beta-SNAPSHOT.aar",
          "url": "native-Beta-SNAPSHOT.aar",
          "size": 16484890,
          "sha512": "585771278d85579d0998436ce76a9c34a9323aed42c92d1fe2d14d2728be9b44bc1961aca86a6a78dc55d59dace5f32dd60cef4683a7602864efc38a7a2e77c5",
          "sha256": "48e6c4eafd984a3a7b6bdd1c9074d61f9fb6ca8a329bc2262ba47e9d0f0471e7",
          "sha1": "f82c673395b63ee70c15961d48f7ff1eb7c36f08",
          "md5": "bd75f8cd000bf8068d2847383a8abe30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Beta-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Beta-SNAPSHOT.aar",
          "url": "native-Beta-SNAPSHOT.aar",
          "size": 16484890,
          "sha512": "585771278d85579d0998436ce76a9c34a9323aed42c92d1fe2d14d2728be9b44bc1961aca86a6a78dc55d59dace5f32dd60cef4683a7602864efc38a7a2e77c5",
          "sha256": "48e6c4eafd984a3a7b6bdd1c9074d61f9fb6ca8a329bc2262ba47e9d0f0471e7",
          "sha1": "f82c673395b63ee70c15961d48f7ff1eb7c36f08",
          "md5": "bd75f8cd000bf8068d2847383a8abe30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Beta-SNAPSHOT-sources.jar",
          "url": "native-Beta-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
