{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "native",
    "version": "Beta-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Beta-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Beta-SNAPSHOT.aar",
          "url": "native-Beta-SNAPSHOT.aar",
          "size": 16402236,
          "sha512": "178acfc4f846d305637b3ea669d12e334de473c2728064a1ed285265c1f138068ae413b4c318aa6e2ed0803201cf0883274f28e5548e344069a5c4e8912064b5",
          "sha256": "f95ffd6340b23214054a1356adf1177c40ac325802389db98b17e711d32d3dee",
          "sha1": "598ac38948db0c6827ca5333eb2a6cd58301775b",
          "md5": "b23300ed14ac10de9731050d4e3a8398"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "Beta-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "native-Beta-SNAPSHOT.aar",
          "url": "native-Beta-SNAPSHOT.aar",
          "size": 16402236,
          "sha512": "178acfc4f846d305637b3ea669d12e334de473c2728064a1ed285265c1f138068ae413b4c318aa6e2ed0803201cf0883274f28e5548e344069a5c4e8912064b5",
          "sha256": "f95ffd6340b23214054a1356adf1177c40ac325802389db98b17e711d32d3dee",
          "sha1": "598ac38948db0c6827ca5333eb2a6cd58301775b",
          "md5": "b23300ed14ac10de9731050d4e3a8398"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-Beta-SNAPSHOT-sources.jar",
          "url": "native-Beta-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
