{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Canary-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Canary-SNAPSHOT.aar",
          "url": "core-Canary-SNAPSHOT.aar",
          "size": 1284810,
          "sha512": "9ab8771c4909341893f4957997b72545c418ec979cb1e2f95be8ec88617cdd74af75d064d754d26d474cf152bb9c4afaaea4c22422f4e6d18ba36b4d249ed9d6",
          "sha256": "d7d00941efe33e4521074d0faf1482185badebcac86779ba9f7ceb7d455e3143",
          "sha1": "6963f0f110ccb65e9aab18175e75e5e106669763",
          "md5": "4e5684c5c95aed56338cce09db4fe87d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Canary-SNAPSHOT.aar",
          "url": "core-Canary-SNAPSHOT.aar",
          "size": 1284810,
          "sha512": "9ab8771c4909341893f4957997b72545c418ec979cb1e2f95be8ec88617cdd74af75d064d754d26d474cf152bb9c4afaaea4c22422f4e6d18ba36b4d249ed9d6",
          "sha256": "d7d00941efe33e4521074d0faf1482185badebcac86779ba9f7ceb7d455e3143",
          "sha1": "6963f0f110ccb65e9aab18175e75e5e106669763",
          "md5": "4e5684c5c95aed56338cce09db4fe87d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Canary-SNAPSHOT-sources.jar",
          "url": "core-Canary-SNAPSHOT-sources.jar",
          "size": 13800,
          "sha512": "89e63ad390052a750ab06559542217c765c9af95d8c43663db3e09698639de995dd4bfe816d482524fd91be2b8ac02907f4144bec6fe253e8ddee759769b24cf",
          "sha256": "1e825636e2e1b94aa43f938a1b33173b2bf7247423b4a37fe5261d534bccc49e",
          "sha1": "723bfb874b878944300d180045d0df3058525cb4",
          "md5": "bb693a5bb445505d7b5797283b37ac8c"
        }
      ]
    }
  ]
}
