{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Canary-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Canary-SNAPSHOT.aar",
          "url": "core-Canary-SNAPSHOT.aar",
          "size": 1284300,
          "sha512": "bbd111cac909b3629d73fb25628b1e93094cfc1450b3f9c15f09d74ab2339766d65a2df93cb3d968022a214b624fd71450ea65356edcaae0e2c9beb504784f34",
          "sha256": "b85dc0b80078b7d87aeaeada0006721362bffca13e67848513b76df3b8042a61",
          "sha1": "e5aacbe514f023e102fcb3f9a0d7a5fe4411a9a8",
          "md5": "6eb2abe533b2a976532c3ec66c2c3e75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Canary-SNAPSHOT.aar",
          "url": "core-Canary-SNAPSHOT.aar",
          "size": 1284300,
          "sha512": "bbd111cac909b3629d73fb25628b1e93094cfc1450b3f9c15f09d74ab2339766d65a2df93cb3d968022a214b624fd71450ea65356edcaae0e2c9beb504784f34",
          "sha256": "b85dc0b80078b7d87aeaeada0006721362bffca13e67848513b76df3b8042a61",
          "sha1": "e5aacbe514f023e102fcb3f9a0d7a5fe4411a9a8",
          "md5": "6eb2abe533b2a976532c3ec66c2c3e75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Canary-SNAPSHOT-sources.jar",
          "url": "core-Canary-SNAPSHOT-sources.jar",
          "size": 13801,
          "sha512": "4c5054af1b27894334428f4873a8374605fb0be6b755fec62ff0480f5072a7a4935e680b4a60cedfabdecbb01f466cea118b0fc8421e4ef62934cf6839176bb5",
          "sha256": "85895bfddcada1c55733170c19e58f0b556b80e4734a3f9e147df21e7f0e19e3",
          "sha1": "c982b77b23d2db56ce1fc8a28e8261be1e72092d",
          "md5": "a6b7a31a12a8fb3a130079b83405221c"
        }
      ]
    }
  ]
}
