{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "core",
    "version": "Canary-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Canary-SNAPSHOT.aar",
          "url": "core-Canary-SNAPSHOT.aar",
          "size": 1281993,
          "sha512": "bf9215a046f0804cac311c16aec9308e2d2887fa1f92e1eedaa5ab48b5ed51f56fed1579fcc8f1c5368d7ca62137892f0f69371b435a23a279b50ff93b7a891f",
          "sha256": "c9097e7a5fd2d19263c90c675c4eb131ac73f8f762f9eb34a198f1b4e6ba115e",
          "sha1": "f13a84b3a258597419a022e8c1da3ffaba919eaf",
          "md5": "1bc1b86d41570c60433a4a7dc29aad18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.34.1"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cronet",
          "version": {
            "requires": "18.1.0"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.huawei.hms",
          "module": "hquic-provider",
          "version": {
            "requires": "5.0.2.300"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.chromium.net",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-Canary-SNAPSHOT.aar",
          "url": "core-Canary-SNAPSHOT.aar",
          "size": 1281993,
          "sha512": "bf9215a046f0804cac311c16aec9308e2d2887fa1f92e1eedaa5ab48b5ed51f56fed1579fcc8f1c5368d7ca62137892f0f69371b435a23a279b50ff93b7a891f",
          "sha256": "c9097e7a5fd2d19263c90c675c4eb131ac73f8f762f9eb34a198f1b4e6ba115e",
          "sha1": "f13a84b3a258597419a022e8c1da3ffaba919eaf",
          "md5": "1bc1b86d41570c60433a4a7dc29aad18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-Canary-SNAPSHOT-sources.jar",
          "url": "core-Canary-SNAPSHOT-sources.jar",
          "size": 13799,
          "sha512": "9308d636cefde9240fa54dc85b91f0234f5793e7012c7cff2b71013ecd3b849112779d5b830ecd6af26c17e2aa244d85b783323e6071d8b4fb705ad6e7f321f9",
          "sha256": "b9740e0364057ff8c8b0a5d2595356293ba9e37848f02250f2344a2a534e81df",
          "sha1": "7e898d4496da7b7418ad4275588beaf1757384a8",
          "md5": "718e58c5caf8fa1ab4050f2493540c49"
        }
      ]
    }
  ]
}
