{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "okhttp",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-0.0.1.aar",
          "url": "okhttp-0.0.1.aar",
          "size": 11106,
          "sha512": "1ae15bf41cfc07f15c77bab1d6244bc78e7454e2853a34e5573d79fa525f7da7a52cfd9e6453270db8448030e6529039c6d9e8d2190291f96519d4ae8f44e0e4",
          "sha256": "df650d8c3e80aa17b3272eba61cb4e87a2cc966752a6fddbd2d5e8e48489bbaa",
          "sha1": "8cac0e5e8cd8965420eec4c0acef3c50451981fe",
          "md5": "a2755776962b711002156ba130648d43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "me.ag2s.cronet",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-0.0.1.aar",
          "url": "okhttp-0.0.1.aar",
          "size": 11106,
          "sha512": "1ae15bf41cfc07f15c77bab1d6244bc78e7454e2853a34e5573d79fa525f7da7a52cfd9e6453270db8448030e6529039c6d9e8d2190291f96519d4ae8f44e0e4",
          "sha256": "df650d8c3e80aa17b3272eba61cb4e87a2cc966752a6fddbd2d5e8e48489bbaa",
          "sha1": "8cac0e5e8cd8965420eec4c0acef3c50451981fe",
          "md5": "a2755776962b711002156ba130648d43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-0.0.1-sources.jar",
          "url": "okhttp-0.0.1-sources.jar",
          "size": 6720,
          "sha512": "63a9dc1b60b41b571412dde020d37294f4f8ee7f278e567000fac90306e62c718f9250ae151797e4da0f82659a688c544c19afcc73dc46a91e03501728d0d1a2",
          "sha256": "99158288c7862b5a730e39237900af94ccaf2bed4edae3144b24afcf77020713",
          "sha1": "64805d26736f558f946167e65d1d1efaba52782e",
          "md5": "c6ba51d194e023417e67f1a8a6970c6b"
        }
      ]
    }
  ]
}
