name: Update Cronet Beta

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'ag2s20150909' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check Beta Cronet Updates
        run: |
          echo "获取cronet最新版本"
          source .github/scripts/cronet.sh Beta
          echo "PR_TITLE=Bump Beta cronet from $current_cronet_version to $lastest_cronet_version " >> $GITHUB_ENV
          echo "PR_BODY=Changes in the [Git log](https://github.com/chromium/chromium/compare/$current_cronet_version..$lastest_cronet_version)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.PR_TITLE }}
          commit-message: |
            ${{ env.PR_TITLE }}
            - ${{ env.PR_BODY }}
          body: ${{ env.PR_BODY }}
          branch: Beta
          delete-branch: true
          add-paths: |
            *cronet*jar
            *cronet.json
            *cronet*.so
            *cronet*.so.js
            *gradle.properties
            repo/**
          